version: '2'

services:

  mariadb:

    image: 'docker.io/bitnami/mariadb:10.3-debian-10'

    environment:

      - ALLOW_EMPTY_PASSWORD=yes

      - MARIADB_USER=bn_drupal

      - MARIADB_DATABASE=bitnami_drupal

    volumes:

      - 'mariadb_data:/bitnami'

  drupal:

    image: 'docker.io/bitnami/drupal:9-debian-10'

    environment:

      - MARIADB_HOST=mariadb

      - MARIADB_PORT_NUMBER=3306

      - DRUPAL_DATABASE_USER=bn_drupal

      - DRUPAL_DATABASE_NAME=bitnami_drupal

      - ALLOW_EMPTY_PASSWORD=yes

    ports:

      - '8081:8080'

      - '8441:8443'

      

    volumes:

      - 'drupal_data:/bitnami'

    depends_on:

      - mariadb

volumes:

  mariadb_data:

    driver: local

  drupal_data:

    driver: local
