version: '2'

services:

  mariadb:

    image: 'docker.io/bitnami/mariadb:10.3-debian-10'

    container_name: db_moodle

    environment:

      - MARIADB_USER=bn_moodle

      - MARIADB_DATABASE=bitnami_moodle

      - ALLOW_EMPTY_PASSWORD=yes

    volumes:

      - 'mariadb_data:/bitnami'


  moodle:

    image: 'docker.io/bitnami/moodle:3-debian-10'

    container_name: moodle

    environment:

      - MARIADB_HOST=db_moodle

      - MARIADB_PORT_NUMBER=3306

      - MOODLE_DATABASE_USER=bn_moodle

      - MOODLE_DATABASE_NAME=bitnami_moodle

      - ALLOW_EMPTY_PASSWORD=yes

    ports:

      - '8082:8080'

      - '8442:8443'

    

    volumes:

      - 'moodle_data:/bitnami'

    depends_on:

      - mariadb


volumes:

  mariadb_data:

    driver: local

  moodle_data:

    driver: local

It should be noted that 8082 & 8442 are ports which have been arbitrary chosen & can be anything valid. When when finds the IP address using docker network inspect moodle_default the webpage can be accessed using 172.24.0.1:8082 as the IP address of moodle_default in my case was 172.24.0.1. In case the program is being run on Ubuntu 18.04 just replace 8080 with 80 & 8443 with 443 above. I have already tested it and find it strange why one need to make these changes. It appears the tcp port defaults have been changed due to some reason.

For Opencart (updated on 24th July 2020)

docker-compose.yml file contents will be

version: '2'

services:

  mariadb:

    image: 'docker.io/bitnami/mariadb:10.3-debian-10'

    environment:

      - MARIADB_USER=bn_opencart

      - MARIADB_DATABASE=bitnami_opencart

      - ALLOW_EMPTY_PASSWORD=yes

    volumes:

      - 'mariadb_data:/bitnami'

  opencart:

    image: 'docker.io/bitnami/opencart:3.0.3-3'

    environment:

      - MARIADB_HOST=mariadb

      - MARIADB_PORT_NUMBER=3306

      - OPENCART_DATABASE_USER=bn_opencart

      - OPENCART_DATABASE_NAME=bitnami_opencart

      - OPENCART_HOST=localhost

      - ALLOW_EMPTY_PASSWORD=yes

    ports:

      - '80:80'

      - '443:443'

      - '587:587'

     

    expose:

      - '80'

      - '587'

      - '443'

 

    volumes:

      - 'opencart_data:/bitnami'

    depends_on:

      - mariadb

volumes:

  mariadb_data:

    driver: local

  opencart_data:

    driver: local
